### ISSUE TITLE
Virtual texture construction loses RGB color data

### ISSUE THREAD

**Issue by floxay** [FabianFG/CUE4Parse#147] opened 2024-07-15 00:04 UTC
I *suspect* it's an issue with how the individual tiles are drawn onto the canvas, or something else, but Skia(Sharp) related.

Example asset:
Game: `The First Descendant`
Path: `M1/Content/Characters/PC/MESH/004/A/Skel/SKIN/VAR/HEAD/Material/000/Texture/PC_004_A0101_Head_000_P.uasset`

<details>
<summary>Current RGBA data (extracted texture):</summary>

![image](https://github.com/user-attachments/assets/7e0a28ca-a8a3-457a-b0e1-6f6ab8ffd217)
</details>

<details>
<summary>Current RGB data (alpha disabled):</summary>

![image](https://github.com/user-attachments/assets/b1d1a729-e119-43f1-ad59-58a245e307ab)
</details>

<details>
<summary>Expected RGB data (alpha disabled):</summary>

![image](https://github.com/user-attachments/assets/2f725e92-a112-4569-8fcc-1d60ef4cc1dd)
</details>

**Comment by 4sval** [comment] 2024-07-15 08:15
what is the pixel format of these textures

**Comment by floxay** [comment] 2024-07-15 08:29
The example uses `PF_DXT5` (BC3).

**Comment by 4sval** [comment] 2024-07-15 08:34
so I guess the problem is [here](https://github.com/FabianFG/CUE4Parse/blob/master/CUE4Parse-Conversion/Textures/TextureDecoder.cs#L62C66-L62C117)
can you try with `SKAlphaType.Unknown`?

**Comment by floxay** [comment] 2024-07-15 12:08
That results in an exception:
![image](https://github.com/user-attachments/assets/9008c1c8-c127-44c0-a070-ef896a73c7bd)

Unpremultiplied should be correct, and it most likely is correct because if I return the first tile, skipping the canvas draws I get the following:
![image](https://github.com/user-attachments/assets/408bece1-158a-4141-b3c6-851baeba6730)
This is the RGB data and looks correct (if we ignore the border), alpha also looks OK but I disabled it here, so I still suspect that it is an issue with `canvas.DrawBitmap()`, or it is incorrectly used here.

**Comment by NotOfficer** [comment] 2024-07-16 03:17
Should be fixed in https://github.com/FabianFG/CUE4Parse/tree/virtual-texture-rgb-fix.
Can you confirm/test?

**Comment by floxay** [comment] 2024-07-16 06:27
> Should be fixed in [`virtual-texture-rgb-fix`](https://github.com/FabianFG/CUE4Parse/tree/virtual-texture-rgb-fix?rgh-link-date=2024-07-16T03%3A17%3A57Z). Can you confirm/test?

Looks perfect, thanks Offi!

**Closed** 2024-07-17 20:25 UTC
